name: finview_lite
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  # Core
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # State management
  flutter_riverpod: ^3.3.2

  # Charts
  fl_chart: ^1.2.0

  # Persistence
  shared_preferences: ^2.5.3

dev_dependencies:
  # Testing
  flutter_test:
    sdk: flutter
  riverpod: ^3.3.2

  # Linting
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/portfolio.json
